# Generated by Django 5.2.17 on 2026-08-28 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_add_document_chunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=255)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetrievedChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('similarity_score', models.FloatField()),
                ('excerpt', models.TextField()),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrieval_records', to='documents.documentchunk')),
                ('question_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieved_chunks', to='qa.questionanswer')),
            ],
            options={
                'ordering': ['question_answer_id', 'rank'],
                'constraints': [models.UniqueConstraint(fields=('question_answer', 'rank'), name='unique_question_answer_rank'), models.UniqueConstraint(fields=('question_answer', 'chunk'), name='unique_question_answer_chunk'), models.CheckConstraint(condition=models.Q(('rank__gt', 0)), name='retrieved_chunk_rank_positive'), models.CheckConstraint(condition=models.Q(('similarity_score__gte', -1.0), ('similarity_score__lte', 1.0)), name='retrieved_chunk_score_valid'), models.CheckConstraint(condition=models.Q(('excerpt', ''), _negated=True), name='retrieved_chunk_excerpt_not_empty')],
            },
        ),
    ]
