# Generated by Django 5.2.17 on 2026-08-27 07:47

import documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/%d/', validators=[documents.validators.validate_docx_file]),
        ),
    ]
