# Generated by Django 5.2.17 on 2026-08-27 09:27

import django.db.models.deletion
import pgvector.django.halfvec
import pgvector.django.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('chunk_index', models.PositiveIntegerField()),
                ('start_offset', models.PositiveIntegerField()),
                ('end_offset', models.PositiveIntegerField()),
                ('token_count', models.PositiveIntegerField()),
                ('embedding', pgvector.django.halfvec.HalfVectorField(blank=True, dimensions=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=['halfvec_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_document_chunk_index'), models.CheckConstraint(condition=models.Q(('content', ''), _negated=True), name='chunk_content_not_empty'), models.CheckConstraint(condition=models.Q(('end_offset__gt', models.F('start_offset'))), name='chunk_offsets_valid'), models.CheckConstraint(condition=models.Q(('token_count__gt', 0)), name='chunk_token_count_positive')],
            },
        ),
    ]
