DEFAULT_CHAT_MODEL = (
    "nvidia/nemotron-3-super-120b-a12b:free"
)

RETRIEVED_CHUNK_EXCERPT_MAX_CHARACTERS = 1000
QUESTION_ERROR_MESSAGE_MAX_CHARACTERS = 2000

QUESTION_MAX_CHARACTERS = 4000
QUESTION_DOCUMENT_FILTER_MAX_ITEMS = 100
